'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class aprovacao

    '''<summary>
    '''formulario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formulario As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtColCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColCodigo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtProCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProCodigo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtDataInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataInicio As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtDataFim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataFim As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''ddlProjeto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProjeto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlMes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlAno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAno As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCompetencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompetencia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''statusAprovacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents statusAprovacao As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''divPaginas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPaginas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''paginas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paginas As Global.System.Web.UI.WebControls.DataPager

    '''<summary>
    '''lblTeste control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeste As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''divCalendario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCalendario As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblColNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblColModulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColModulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblColNivel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColNivel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMesReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMesReferencia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPeriodo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriodo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCliente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProjeto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjeto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblResponsavel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResponsavel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha5 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha6 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha7 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha8 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha9 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha10 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha11 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha12 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha13 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha14 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha15 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha16 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha17 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha18 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha19 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha20 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha21 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha22 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha23 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha24 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha25 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha26 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha27 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha28 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha29 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha30 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linha31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linha31 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDia31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDia31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntrada31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntrada31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEntAlmoco31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntAlmoco31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaiAlmoco31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaiAlmoco31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSaida31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaida31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNormal31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNormal31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExtra31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtra31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAtividades31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAtividades31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalNormais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalNormais As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalExtras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalExtras As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensagem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnAprovar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAprovar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnReprovar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReprovar As Global.System.Web.UI.WebControls.Button
End Class
